import type { DummyCampaignBrief } from "@/lib/dummy/types";

export const dummyCampaignBriefs: readonly DummyCampaignBrief[] = [
  {
    id: "brief_001",
    umkmId: "umkm_001",
    orderId: "order_001",
    businessName: "Bakso Mas Adi",
    businessCategory: "Kuliner",
    promotedFocus: "Menu bakso urat dan promo paket keluarga",
    campaignGoal: "Meningkatkan kunjungan pelanggan sekitar saat jam makan siang.",
    targetAudience: ["pekerja kantor", "keluarga muda", "pelajar sekitar"],
    contentPlatforms: ["Instagram Reels", "TikTok"],
    contentStyle: ["hangat", "menggugah selera", "natural"],
    referenceLinks: ["https://example.com/reference/bakso-reels"],
    deadline: "2026-06-12",
    additionalNotes:
      "Tonjolkan proses penyajian, kuah panas, dan suasana warung yang ramah.",
    assetUrls: ["/images/dummy/briefs/bakso-menu.jpg"],
    status: "linked_to_order",
  },
  {
    id: "brief_002",
    umkmId: "umkm_002",
    orderId: "order_002",
    businessName: "Kopi Sudut Kota",
    businessCategory: "Minuman",
    promotedFocus: "Menu kopi susu dan suasana kerja santai",
    campaignGoal: "Memperkenalkan kedai sebagai tempat singgah untuk kerja dan diskusi.",
    targetAudience: ["mahasiswa", "remote worker", "komunitas kreatif"],
    contentPlatforms: ["Instagram", "Google Business Profile"],
    contentStyle: ["calm", "modern", "cozy"],
    referenceLinks: ["https://example.com/reference/kopi-photo"],
    deadline: "2026-06-15",
    additionalNotes:
      "Gunakan tone visual yang lembut dengan fokus pada meja, minuman, dan aktivitas pelanggan.",
    assetUrls: ["/images/dummy/briefs/kopi-menu.jpg"],
    status: "linked_to_order",
  },
  {
    id: "brief_003",
    umkmId: "umkm_004",
    orderId: "order_003",
    businessName: "Batik Loka",
    businessCategory: "Fashion Lokal",
    promotedFocus: "Koleksi batik kerja motif Loka Sore",
    campaignGoal: "Membuat koleksi baru terasa modern dan cocok untuk profesional muda.",
    targetAudience: ["profesional muda", "pecinta budaya", "pembeli hadiah"],
    contentPlatforms: ["Instagram Feed", "Instagram Story"],
    contentStyle: ["premium", "elegan", "minimal"],
    referenceLinks: ["https://example.com/reference/batik-feed"],
    deadline: "2026-06-18",
    additionalNotes:
      "Hindari visual yang terlalu ramai. Fokus pada detail motif, bahan, dan styling kerja.",
    assetUrls: ["/images/dummy/briefs/batik-collection.jpg"],
    status: "linked_to_order",
  },
  {
    id: "brief_004",
    umkmId: "umkm_005",
    orderId: "order_004",
    businessName: "Keripik Bu Sari",
    businessCategory: "Camilan Lokal",
    promotedFocus: "Keripik pedas varian level 3 dan level 5",
    campaignGoal: "Meningkatkan minat coba dari pelanggan muda yang menyukai camilan pedas.",
    targetAudience: ["anak muda", "komunitas kampus", "pelanggan oleh-oleh"],
    contentPlatforms: ["TikTok", "Instagram Reels"],
    contentStyle: ["ceria", "jujur", "enerjik"],
    referenceLinks: ["https://example.com/reference/spicy-snack-review"],
    deadline: "2026-06-20",
    additionalNotes:
      "Review harus menonjolkan rasa, tekstur, dan reaksi pertama saat mencoba level pedas.",
    assetUrls: ["/images/dummy/briefs/keripik-varian.jpg"],
    status: "linked_to_order",
  },
  {
    id: "brief_005",
    umkmId: "umkm_003",
    orderId: "order_005",
    businessName: "Roti Lembut Pagi",
    businessCategory: "Bakery",
    promotedFocus: "Paket roti sarapan keluarga",
    campaignGoal: "Menguatkan positioning sebagai pilihan roti segar untuk pagi hari.",
    targetAudience: ["keluarga", "pegawai kantor", "komunitas sekolah"],
    contentPlatforms: ["Instagram Feed", "WhatsApp Business"],
    contentStyle: ["bersih", "hangat", "ramah keluarga"],
    referenceLinks: ["https://example.com/reference/roti-feed"],
    deadline: "2026-06-08",
    additionalNotes:
      "Gunakan copy yang mudah dipahami dan visual yang cocok untuk promo pagi.",
    assetUrls: ["/images/dummy/briefs/roti-pagi.jpg"],
    status: "linked_to_order",
  },
  {
    id: "brief_006",
    umkmId: "umkm_004",
    orderId: "order_006",
    businessName: "Batik Loka",
    businessCategory: "Fashion Lokal",
    promotedFocus: "Campaign styling batik untuk akhir pekan",
    campaignGoal: "Menguji ide campaign TikTok untuk audiens yang mencari inspirasi outfit lokal.",
    targetAudience: ["profesional muda", "komunitas kreatif", "pecinta budaya"],
    contentPlatforms: ["TikTok", "Instagram Reels"],
    contentStyle: ["modern", "rapi", "percaya diri"],
    referenceLinks: ["https://example.com/reference/batik-campaign"],
    deadline: "2026-06-22",
    additionalNotes:
      "Campaign dibatalkan karena batas pembayaran dummy sudah lewat sebelum kreator mulai produksi.",
    assetUrls: ["/images/dummy/briefs/batik-campaign.jpg"],
    status: "linked_to_order",
  },
];
