import type { DummyCreatorProfile } from "@/lib/dummy/types";

export const dummyCreators: readonly DummyCreatorProfile[] = [
  {
    id: "creator_001",
    userId: "user_creator_001",
    displayName: "Raka Visual",
    niche: "Video kuliner dan reels UMKM",
    city: "Jakarta Selatan",
    province: "DKI Jakarta",
    bio: "Content creator yang fokus membantu UMKM kuliner tampil lebih menarik lewat video pendek yang rapi dan natural.",
    skills: ["video reels", "food styling", "script pendek", "editing mobile"],
    avatarUrl: "/images/dummy/creators/raka-visual.jpg",
    bannerUrl: "/images/dummy/creators/raka-visual-banner.jpg",
    instagramUrl: "https://instagram.com/rakavisual",
    tiktokUrl: "https://tiktok.com/@rakavisual",
    availabilityStatus: "available",
    startingPrice: 150000,
    averageRating: 4.9,
    completedOrdersCount: 86,
    responseTimeHours: 2,
    isVerified: true,
    isFeatured: true,
  },
  {
    id: "creator_002",
    userId: "user_creator_002",
    displayName: "Nabila Creative",
    niche: "Desain feed Instagram dan brand visual",
    city: "Bandung",
    province: "Jawa Barat",
    bio: "Marketer visual dengan pendekatan minimalis untuk desain feed, konten promosi, dan kampanye lokal.",
    skills: ["desain feed", "brand kit", "copywriting ringan", "content planning"],
    avatarUrl: "/images/dummy/creators/nabila-creative.jpg",
    bannerUrl: "/images/dummy/creators/nabila-creative-banner.jpg",
    instagramUrl: "https://instagram.com/nabilacreative",
    tiktokUrl: "https://tiktok.com/@nabilacreative",
    availabilityStatus: "limited",
    startingPrice: 120000,
    averageRating: 4.8,
    completedOrdersCount: 74,
    responseTimeHours: 4,
    isVerified: true,
    isFeatured: true,
  },
  {
    id: "creator_003",
    userId: "user_creator_003",
    displayName: "Dimas Review",
    niche: "Review produk lokal dan konten testimonial",
    city: "Surabaya",
    province: "Jawa Timur",
    bio: "Kreator review yang biasa mengemas cerita manfaat produk lokal dengan gaya santai dan mudah dipercaya.",
    skills: ["review produk", "voice over", "storytelling", "ugc video"],
    avatarUrl: "/images/dummy/creators/dimas-review.jpg",
    bannerUrl: "/images/dummy/creators/dimas-review-banner.jpg",
    instagramUrl: "https://instagram.com/dimasreview",
    tiktokUrl: "https://tiktok.com/@dimasreview",
    availabilityStatus: "available",
    startingPrice: 200000,
    averageRating: 4.7,
    completedOrdersCount: 63,
    responseTimeHours: 3,
    isVerified: true,
    isFeatured: false,
  },
  {
    id: "creator_004",
    userId: "user_creator_004",
    displayName: "Sinta Studio",
    niche: "Foto produk dan visual katalog UMKM",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    bio: "Studio kreatif kecil yang membantu UMKM membuat foto produk, konsep visual, dan konten promosi yang konsisten.",
    skills: ["foto produk", "lighting", "styling", "retouching"],
    avatarUrl: "/images/dummy/creators/sinta-studio.jpg",
    bannerUrl: "/images/dummy/creators/sinta-studio-banner.jpg",
    instagramUrl: "https://instagram.com/sintastudio",
    tiktokUrl: "https://tiktok.com/@sintastudio",
    availabilityStatus: "busy",
    startingPrice: 175000,
    averageRating: 4.9,
    completedOrdersCount: 91,
    responseTimeHours: 6,
    isVerified: true,
    isFeatured: true,
  },
  {
    id: "creator_005",
    userId: "user_creator_005",
    displayName: "Fadd Graphics",
    niche: "Desain promosi dan grafis campaign UMKM",
    city: "Semarang",
    province: "Jawa Tengah",
    bio: "Desainer grafis yang membuat materi promosi digital untuk UMKM dengan gaya bersih, informatif, dan mudah dipakai.",
    skills: ["poster digital", "desain feed", "template promosi", "layout grafis"],
    avatarUrl: "/images/dummy/creators/fadd-graphics.jpg",
    bannerUrl: "/images/dummy/creators/fadd-graphics-banner.jpg",
    instagramUrl: "https://instagram.com/faddgraphics",
    tiktokUrl: "https://tiktok.com/@faddgraphics",
    availabilityStatus: "available",
    startingPrice: 150000,
    averageRating: 4.6,
    completedOrdersCount: 52,
    responseTimeHours: 5,
    isVerified: false,
    isFeatured: false,
  },
  {
    id: "creator_006",
    userId: "user_creator_006",
    displayName: "Arkan Media",
    niche: "Campaign TikTok dan strategi konten lokal",
    city: "Denpasar",
    province: "Bali",
    bio: "Tim marketer yang menyusun campaign pendek untuk membantu UMKM mencoba konten TikTok secara terarah.",
    skills: ["campaign UMKM", "strategi konten", "video tiktok", "analytics ringan"],
    avatarUrl: "/images/dummy/creators/arkan-media.jpg",
    bannerUrl: "/images/dummy/creators/arkan-media-banner.jpg",
    instagramUrl: "https://instagram.com/arkanmedia",
    tiktokUrl: "https://tiktok.com/@arkanmedia",
    availabilityStatus: "limited",
    startingPrice: 300000,
    averageRating: 4.8,
    completedOrdersCount: 68,
    responseTimeHours: 4,
    isVerified: true,
    isFeatured: true,
  },
];
