import type {
  DummyServiceAddon,
  DummyServicePackage,
  DummyServiceTier,
} from "@/lib/dummy/types";

export const dummyServicePackages: readonly DummyServicePackage[] = [
  {
    id: "service_001",
    creatorId: "creator_001",
    categoryId: "category_001",
    title: "Video Reels Kuliner untuk UMKM",
    slug: "video-reels-kuliner-umkm",
    shortDescription:
      "Video pendek kuliner yang menonjolkan suasana, tekstur, dan ajakan datang ke tempat usaha.",
    description:
      "Paket jasa pembuatan video TikTok/Reels untuk UMKM kuliner, mulai dari konsep singkat, pengambilan gambar sederhana, sampai editing final siap unggah.",
    coverImageUrl: "/images/dummy/services/video-reels-kuliner.jpg",
    basePrice: 150000,
    estimatedDays: 3,
    revisionCount: 1,
    deliverables: ["1 video 15-30 detik", "format vertikal 9:16", "teks overlay dasar"],
    requirements: ["brief campaign", "referensi gaya konten", "alamat kanal sosial"],
    tags: ["kuliner", "reels", "tiktok", "video pendek"],
    isActive: true,
    isFeatured: true,
  },
  {
    id: "service_002",
    creatorId: "creator_002",
    categoryId: "category_002",
    title: "Desain Feed Promosi Fashion Lokal",
    slug: "desain-feed-promosi-fashion",
    shortDescription:
      "Desain feed Instagram yang rapi untuk memperkenalkan koleksi, promo, dan cerita brand fashion lokal.",
    description:
      "Paket desain visual untuk UMKM fashion yang membutuhkan feed Instagram konsisten, premium, dan mudah dipahami calon pelanggan.",
    coverImageUrl: "/images/dummy/services/desain-feed-fashion.jpg",
    basePrice: 120000,
    estimatedDays: 2,
    revisionCount: 1,
    deliverables: ["1 desain feed", "file JPG/PNG", "copy pendek untuk caption"],
    requirements: ["brief campaign", "logo atau identitas visual", "contoh gaya visual"],
    tags: ["fashion", "instagram", "desain feed", "brand visual"],
    isActive: true,
    isFeatured: true,
  },
  {
    id: "service_003",
    creatorId: "creator_003",
    categoryId: "category_004",
    title: "Review Produk Lokal oleh Kreator",
    slug: "review-produk-lokal",
    shortDescription:
      "Konten review natural yang menjelaskan pengalaman memakai produk atau mencoba penawaran UMKM.",
    description:
      "Paket jasa review produk lokal dengan gaya personal, hook singkat, dan sudut pandang yang ramah untuk calon pelanggan baru.",
    coverImageUrl: "/images/dummy/services/review-produk-lokal.jpg",
    basePrice: 200000,
    estimatedDays: 4,
    revisionCount: 1,
    deliverables: ["1 video review", "script ringkas", "caption utama"],
    requirements: ["brief campaign", "poin keunggulan produk", "aturan penyebutan brand"],
    tags: ["review", "ugc", "produk lokal", "testimoni"],
    isActive: true,
    isFeatured: false,
  },
  {
    id: "service_004",
    creatorId: "creator_004",
    categoryId: "category_003",
    title: "Foto Produk untuk Katalog Digital",
    slug: "foto-produk-katalog-digital",
    shortDescription:
      "Foto produk bersih untuk menu, katalog digital, landing page, atau materi promosi UMKM.",
    description:
      "Paket foto produk dengan penataan sederhana, pencahayaan rapi, dan editing warna agar visual lebih siap untuk promosi digital.",
    coverImageUrl: "/images/dummy/services/foto-produk-katalog.jpg",
    basePrice: 175000,
    estimatedDays: 3,
    revisionCount: 1,
    deliverables: ["3 foto final", "warna sudah diedit", "format JPG"],
    requirements: ["brief campaign", "daftar angle prioritas", "referensi visual"],
    tags: ["foto produk", "katalog digital", "visual", "konten promosi"],
    isActive: true,
    isFeatured: true,
  },
  {
    id: "service_005",
    creatorId: "creator_005",
    categoryId: "category_002",
    title: "Desain Promosi dan Branding UMKM",
    slug: "desain-promosi-branding-umkm",
    shortDescription:
      "Materi desain promosi yang bersih untuk feed, story, dan pengumuman campaign UMKM.",
    description:
      "Paket desain grafis untuk UMKM yang membutuhkan materi promosi praktis, konsisten, dan siap digunakan di media sosial.",
    coverImageUrl: "/images/dummy/services/desain-promosi-umkm.jpg",
    basePrice: 150000,
    estimatedDays: 3,
    revisionCount: 1,
    deliverables: ["1 desain feed", "1 desain story", "file JPG/PNG"],
    requirements: ["brief campaign", "teks promo", "warna atau gaya visual pilihan"],
    tags: ["desain promosi", "branding", "instagram", "campaign"],
    isActive: true,
    isFeatured: false,
  },
  {
    id: "service_006",
    creatorId: "creator_006",
    categoryId: "category_006",
    title: "Campaign TikTok UMKM 7 Hari",
    slug: "campaign-tiktok-umkm-7-hari",
    shortDescription:
      "Rangkaian ide konten dan eksekusi video pendek untuk membantu UMKM mencoba campaign TikTok.",
    description:
      "Paket campaign UMKM dengan arahan konsep, produksi konten pendek, dan ringkasan performa sederhana setelah konten berjalan.",
    coverImageUrl: "/images/dummy/services/campaign-tiktok-umkm.jpg",
    basePrice: 300000,
    estimatedDays: 5,
    revisionCount: 2,
    deliverables: ["2 video pendek", "caption utama", "ringkasan insight awal"],
    requirements: ["brief campaign", "tujuan campaign", "contoh konten pembanding"],
    tags: ["campaign UMKM", "tiktok", "strategi konten", "video pendek"],
    isActive: true,
    isFeatured: true,
  },
];

export const dummyServiceTiers: readonly DummyServiceTier[] = [
  {
    id: "tier_service_001_basic",
    servicePackageId: "service_001",
    name: "Basic",
    description: "Video pendek sederhana untuk satu pesan promosi utama.",
    price: 150000,
    estimatedDays: 3,
    revisionCount: 1,
    deliverables: ["1 video 15 detik", "format 9:16"],
    sortOrder: 1,
  },
  {
    id: "tier_service_001_standard",
    servicePackageId: "service_001",
    name: "Standard",
    description: "Video lebih lengkap dengan hook, teks overlay, dan caption utama.",
    price: 300000,
    estimatedDays: 4,
    revisionCount: 2,
    deliverables: ["1 video 30 detik", "teks overlay", "caption utama"],
    sortOrder: 2,
  },
  {
    id: "tier_service_001_premium",
    servicePackageId: "service_001",
    name: "Premium",
    description: "Dua variasi video untuk kebutuhan promosi yang lebih fleksibel.",
    price: 500000,
    estimatedDays: 6,
    revisionCount: 2,
    deliverables: ["2 video 30 detik", "teks overlay", "2 caption promosi"],
    sortOrder: 3,
  },
  {
    id: "tier_service_002_basic",
    servicePackageId: "service_002",
    name: "Basic",
    description: "Satu desain feed promosi dengan layout bersih.",
    price: 120000,
    estimatedDays: 2,
    revisionCount: 1,
    deliverables: ["1 desain feed", "file JPG/PNG"],
    sortOrder: 1,
  },
  {
    id: "tier_service_002_standard",
    servicePackageId: "service_002",
    name: "Standard",
    description: "Paket desain feed dan story untuk satu campaign singkat.",
    price: 220000,
    estimatedDays: 3,
    revisionCount: 2,
    deliverables: ["2 desain feed", "1 desain story", "caption pendek"],
    sortOrder: 2,
  },
  {
    id: "tier_service_002_premium",
    servicePackageId: "service_002",
    name: "Premium",
    description: "Set visual campaign dengan beberapa variasi konten.",
    price: 300000,
    estimatedDays: 4,
    revisionCount: 2,
    deliverables: ["3 desain feed", "2 desain story", "caption promosi"],
    sortOrder: 3,
  },
  {
    id: "tier_service_003_basic",
    servicePackageId: "service_003",
    name: "Basic",
    description: "Review singkat untuk satu sudut pesan utama.",
    price: 200000,
    estimatedDays: 4,
    revisionCount: 1,
    deliverables: ["1 video review", "caption utama"],
    sortOrder: 1,
  },
  {
    id: "tier_service_003_standard",
    servicePackageId: "service_003",
    name: "Standard",
    description: "Review lebih lengkap dengan script dan hook yang disiapkan.",
    price: 350000,
    estimatedDays: 5,
    revisionCount: 2,
    deliverables: ["1 video review", "script ringkas", "caption promosi"],
    sortOrder: 2,
  },
  {
    id: "tier_service_003_premium",
    servicePackageId: "service_003",
    name: "Premium",
    description: "Review mendalam dengan dua versi hook untuk testing konten.",
    price: 550000,
    estimatedDays: 7,
    revisionCount: 2,
    deliverables: ["2 video review", "2 versi hook", "caption promosi"],
    sortOrder: 3,
  },
  {
    id: "tier_service_004_basic",
    servicePackageId: "service_004",
    name: "Basic",
    description: "Foto final sederhana untuk satu kebutuhan promosi.",
    price: 175000,
    estimatedDays: 3,
    revisionCount: 1,
    deliverables: ["3 foto final", "file JPG"],
    sortOrder: 1,
  },
  {
    id: "tier_service_004_standard",
    servicePackageId: "service_004",
    name: "Standard",
    description: "Foto produk dengan variasi angle dan editing warna.",
    price: 325000,
    estimatedDays: 4,
    revisionCount: 2,
    deliverables: ["6 foto final", "variasi angle", "file JPG"],
    sortOrder: 2,
  },
  {
    id: "tier_service_004_premium",
    servicePackageId: "service_004",
    name: "Premium",
    description: "Sesi foto produk lengkap untuk katalog digital dan campaign.",
    price: 500000,
    estimatedDays: 6,
    revisionCount: 2,
    deliverables: ["10 foto final", "layout hero sederhana", "file JPG"],
    sortOrder: 3,
  },
  {
    id: "tier_service_005_basic",
    servicePackageId: "service_005",
    name: "Basic",
    description: "Satu desain promosi siap unggah.",
    price: 150000,
    estimatedDays: 3,
    revisionCount: 1,
    deliverables: ["1 desain feed", "file JPG/PNG"],
    sortOrder: 1,
  },
  {
    id: "tier_service_005_standard",
    servicePackageId: "service_005",
    name: "Standard",
    description: "Materi feed dan story untuk campaign promosi singkat.",
    price: 250000,
    estimatedDays: 4,
    revisionCount: 2,
    deliverables: ["2 desain feed", "1 desain story", "caption pendek"],
    sortOrder: 2,
  },
  {
    id: "tier_service_005_premium",
    servicePackageId: "service_005",
    name: "Premium",
    description: "Paket desain promosi dengan variasi visual lebih lengkap.",
    price: 420000,
    estimatedDays: 6,
    revisionCount: 2,
    deliverables: ["4 desain feed", "2 desain story", "template promosi"],
    sortOrder: 3,
  },
  {
    id: "tier_service_006_basic",
    servicePackageId: "service_006",
    name: "Basic",
    description: "Campaign singkat dengan satu video utama dan arahan caption.",
    price: 300000,
    estimatedDays: 5,
    revisionCount: 1,
    deliverables: ["1 video pendek", "caption utama", "ide konten singkat"],
    sortOrder: 1,
  },
  {
    id: "tier_service_006_standard",
    servicePackageId: "service_006",
    name: "Standard",
    description: "Campaign 7 hari dengan dua video dan arahan jadwal unggah.",
    price: 600000,
    estimatedDays: 7,
    revisionCount: 2,
    deliverables: ["2 video pendek", "2 caption", "jadwal konten 7 hari"],
    sortOrder: 2,
  },
  {
    id: "tier_service_006_premium",
    servicePackageId: "service_006",
    name: "Premium",
    description: "Campaign lebih lengkap dengan strategi konten dan insight awal.",
    price: 950000,
    estimatedDays: 10,
    revisionCount: 3,
    deliverables: ["3 video pendek", "3 caption", "ringkasan insight awal"],
    sortOrder: 3,
  },
];

export const dummyServiceAddons: readonly DummyServiceAddon[] = [
  {
    id: "addon_001",
    name: "Bantuan Brief Campaign",
    description:
      "Kreator membantu merapikan tujuan, sudut pesan, dan arahan konten sebelum pengerjaan dimulai.",
    price: 150000,
    compatibleServiceIds: ["service_001", "service_002", "service_003", "service_006"],
  },
  {
    id: "addon_002",
    name: "Caption Tambahan",
    description: "Tambahan variasi caption promosi untuk kebutuhan testing pesan.",
    price: 50000,
    compatibleServiceIds: ["service_001", "service_002", "service_003", "service_005", "service_006"],
  },
  {
    id: "addon_003",
    name: "Revisi Tambahan",
    description: "Satu putaran revisi ekstra di luar batas revisi paket jasa.",
    price: 75000,
    compatibleServiceIds: [
      "service_001",
      "service_002",
      "service_003",
      "service_004",
      "service_005",
      "service_006",
    ],
  },
  {
    id: "addon_004",
    name: "File Mentah",
    description: "File kerja mentah untuk arsip internal UMKM dan kebutuhan pengembangan konten lanjutan.",
    price: 100000,
    compatibleServiceIds: ["service_001", "service_002", "service_004", "service_005", "service_006"],
  },
  {
    id: "addon_005",
    name: "Pengerjaan Lebih Cepat",
    description: "Prioritas jadwal pengerjaan sesuai ketersediaan kreator.",
    price: 150000,
    compatibleServiceIds: [
      "service_001",
      "service_002",
      "service_003",
      "service_004",
      "service_005",
      "service_006",
    ],
  },
];
