import type { DummyUmkmProfile } from "@/lib/dummy/types";

export const dummyUmkmProfiles: readonly DummyUmkmProfile[] = [
  {
    id: "umkm_001",
    userId: "user_umkm_001",
    businessName: "Bakso Mas Adi",
    businessCategory: "Kuliner",
    ownerName: "Andi Pratama",
    city: "Bekasi",
    province: "Jawa Barat",
    description:
      "Warung bakso rumahan dengan menu bakso urat, mie ayam, dan promo paket keluarga untuk pelanggan sekitar.",
    instagramUrl: "https://instagram.com/baksomasadi",
    whatsappNumber: "+628121110001",
    targetAudience: ["keluarga muda", "pekerja kantor", "pelajar"],
    contentPreference: ["video pendek", "review kuliner", "caption promosi"],
  },
  {
    id: "umkm_002",
    userId: "user_umkm_002",
    businessName: "Kopi Sudut Kota",
    businessCategory: "Minuman",
    ownerName: "Rina Maharani",
    city: "Bandung",
    province: "Jawa Barat",
    description:
      "Kedai kopi kecil dengan suasana tenang, menu kopi susu, mocktail kopi, dan pastry harian.",
    instagramUrl: "https://instagram.com/kopisudutkota",
    whatsappNumber: "+628121110002",
    targetAudience: ["mahasiswa", "remote worker", "komunitas kreatif"],
    contentPreference: ["foto suasana", "video reels", "konten gaya hidup"],
  },
  {
    id: "umkm_003",
    userId: "user_umkm_003",
    businessName: "Roti Lembut Pagi",
    businessCategory: "Bakery",
    ownerName: "Maya Kartika",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    description:
      "Toko roti harian yang fokus pada roti sobek, roti isi, dan hampers sarapan untuk pelanggan lokal.",
    instagramUrl: "https://instagram.com/rotilembutpagi",
    whatsappNumber: "+628121110003",
    targetAudience: ["keluarga", "pegawai kantor", "komunitas sekolah"],
    contentPreference: ["foto produk", "desain feed", "caption promosi"],
  },
  {
    id: "umkm_004",
    userId: "user_umkm_004",
    businessName: "Batik Loka",
    businessCategory: "Fashion Lokal",
    ownerName: "Loka Prasetya",
    city: "Solo",
    province: "Jawa Tengah",
    description:
      "Brand batik modern yang mengangkat motif lokal untuk pakaian kerja, acara keluarga, dan hadiah premium.",
    instagramUrl: "https://instagram.com/batikloka",
    whatsappNumber: "+628121110004",
    targetAudience: ["profesional muda", "pecinta budaya", "pembeli hadiah"],
    contentPreference: ["desain feed", "foto katalog", "video styling"],
  },
  {
    id: "umkm_005",
    userId: "user_umkm_005",
    businessName: "Keripik Bu Sari",
    businessCategory: "Camilan Lokal",
    ownerName: "Sari Aminah",
    city: "Malang",
    province: "Jawa Timur",
    description:
      "Usaha camilan rumahan dengan pilihan keripik pedas, gurih, dan varian rasa musiman untuk pasar anak muda.",
    instagramUrl: "https://instagram.com/keripikbusari",
    whatsappNumber: "+628121110005",
    targetAudience: ["anak muda", "komunitas kampus", "pelanggan oleh-oleh"],
    contentPreference: ["review produk", "video tiktok", "campaign UMKM"],
  },
];
