import type { DummyUser } from "@/lib/dummy/types";

export const dummyUsers: readonly DummyUser[] = [
  {
    id: "user_umkm_001",
    role: "umkm",
    name: "Andi Pratama",
    email: "andi@baksomasadi.example",
    avatarUrl: "/images/dummy/users/andi-pratama.jpg",
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "user_umkm_002",
    role: "umkm",
    name: "Rina Maharani",
    email: "rina@kopisudutkota.example",
    avatarUrl: "/images/dummy/users/rina-maharani.jpg",
    createdAt: "2026-01-08T10:15:00.000Z",
  },
  {
    id: "user_umkm_003",
    role: "umkm",
    name: "Maya Kartika",
    email: "maya@rotilembutpagi.example",
    avatarUrl: "/images/dummy/users/maya-kartika.jpg",
    createdAt: "2026-01-12T08:45:00.000Z",
  },
  {
    id: "user_umkm_004",
    role: "umkm",
    name: "Loka Prasetya",
    email: "loka@batikloka.example",
    avatarUrl: "/images/dummy/users/loka-prasetya.jpg",
    createdAt: "2026-01-20T13:20:00.000Z",
  },
  {
    id: "user_umkm_005",
    role: "umkm",
    name: "Sari Aminah",
    email: "sari@keripikbusari.example",
    avatarUrl: "/images/dummy/users/sari-aminah.jpg",
    createdAt: "2026-01-26T11:05:00.000Z",
  },
  {
    id: "user_creator_001",
    role: "creator",
    name: "Raka Visual",
    email: "hello@rakavisual.example",
    avatarUrl: "/images/dummy/creators/raka-visual.jpg",
    createdAt: "2025-12-10T07:30:00.000Z",
  },
  {
    id: "user_creator_002",
    role: "creator",
    name: "Nabila Creative",
    email: "nabila@creative.example",
    avatarUrl: "/images/dummy/creators/nabila-creative.jpg",
    createdAt: "2025-12-12T09:00:00.000Z",
  },
  {
    id: "user_creator_003",
    role: "creator",
    name: "Dimas Review",
    email: "dimas@review.example",
    avatarUrl: "/images/dummy/creators/dimas-review.jpg",
    createdAt: "2025-12-18T12:10:00.000Z",
  },
  {
    id: "user_creator_004",
    role: "creator",
    name: "Sinta Studio",
    email: "sinta@studio.example",
    avatarUrl: "/images/dummy/creators/sinta-studio.jpg",
    createdAt: "2025-12-21T14:25:00.000Z",
  },
  {
    id: "user_creator_005",
    role: "creator",
    name: "Fadd Graphics",
    email: "fadd@graphics.example",
    avatarUrl: "/images/dummy/creators/fadd-graphics.jpg",
    createdAt: "2025-12-28T10:35:00.000Z",
  },
  {
    id: "user_creator_006",
    role: "creator",
    name: "Arkan Media",
    email: "arkan@media.example",
    avatarUrl: "/images/dummy/creators/arkan-media.jpg",
    createdAt: "2026-01-02T15:50:00.000Z",
  },
  {
    id: "user_admin_001",
    role: "admin",
    name: "Admin Ruang Usaha",
    email: "admin@ruangusahakita.example",
    avatarUrl: "/images/dummy/users/admin-ruang-usaha.jpg",
    createdAt: "2025-11-20T08:00:00.000Z",
  },
];
